// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5O8B-LvO1HXceDxW_w6ChnUrkun5itE',
    appId: '1:1050327724211:web:97ad7995a8cbb607d440c6',
    messagingSenderId: '1050327724211',
    projectId: 'labmaid-demo',
    authDomain: 'labmaid-demo.firebaseapp.com',
    storageBucket: 'labmaid-demo.firebasestorage.app',
    measurementId: 'G-62KWEK05JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1Sspz2LlIAASDzovYDaNzQ0CfMhuZnQ',
    appId: '1:1050327724211:android:16c088492eda05c0d440c6',
    messagingSenderId: '1050327724211',
    projectId: 'labmaid-demo',
    storageBucket: 'labmaid-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPzO9e3AP27sVL9fdCrOgObIIuSzu6VY',
    appId: '1:1050327724211:ios:310620c64e54fc39d440c6',
    messagingSenderId: '1050327724211',
    projectId: 'labmaid-demo',
    storageBucket: 'labmaid-demo.firebasestorage.app',
    iosBundleId: 'com.algorithm.labmaid',
  );

}